### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'HetNet_data/memory_data'

### ISSUE THREAD

**Issue by zarah93** [moooontoo/Latency-Equalization-E2E-NS-RL#3]
Hi @moooontoo 
I hope you are doing well 
I appreciate the work that you and your team have done, and I'm starting to grasp it. Could you help me understand why these errors are happening and suggest what adjustments I should make to ensure everything works smoothly? Thank you in advance for your assistance and guidance.
Traceback (most recent call last):
  File "e:\Latency-Equalization-E2E-NS-RL-main\code\DSDP.py", line 43, in <module>
    l1, r, ssl =rlRan(sla, target_net, act_net, train)   #0.001的学习率，300个episode得到一个接近最终的结果
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Latency-Equalization-E2E-NS-RL-main\code\ran.py", line 124, in rlRan
    memory = ReplayMemory(AgentConfig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Latency-Equalization-E2E-NS-RL-main\code\replay_memory.py", line 19, in __init__
    if not (self.is_empty()):  # is_empty()是空的，返回true
            ^^^^^^^^^^^^^^^
  File "e:\Latency-Equalization-E2E-NS-RL-main\code\replay_memory.py", line 97, in is_empty
    filenames1 = os.listdir(Tools.memory_data)  # Tools.memory_data为地址
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'HetNet_data/memory_data'

**Comment by XMstudying** [comment]
你好学长，我也是西邮的，代码有问题请教你，可以留下联系方式吗。谢谢学长！！！！

**Comment by zarah93** [comment]
@XMstudying did you have the same issue?
